"""Calibrate frozen trusted local experiments, lock selections, then consume test."""

import inspect
import json
from hashlib import sha256
from importlib.metadata import version
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from credit_risk import __version__
from credit_risk.data.loaders import load_origination_csv
from credit_risk.data.validation import ORIGINATION_FEATURES, ORIGINATION_TARGET
from credit_risk.features.origination import OriginationFeatures
from credit_risk.models.calibration import CalibratedPDModel, ProbabilityCalibrator
from credit_risk.models.pd import predict_probability, run_origination_experiment, split_origination
from credit_risk.utils.config import ModelConfig
from credit_risk.validation.backtesting import segment_diagnostics
from credit_risk.validation.diagnostics import (
    calibration_edges,
    group_bootstrap_comparison,
    reliability_diagnostics,
)
from credit_risk.validation.metrics import binary_metrics
from credit_risk.validation.settings import ValidationConfig


def digest(path):
    return sha256(Path(path).read_bytes()).hexdigest()


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, allow_nan=False) + "\n", encoding="utf-8")


def verify_experiment(csv_path, run_dir):
    """Verify before deserialization. Only use artifacts generated by this trusted lab.

    Checksums detect accidental changes; they do not authenticate an untrusted pickle.
    """
    run_dir = Path(run_dir)
    manifest = json.loads((run_dir / "experiment.json").read_text(encoding="utf-8"))
    if digest(csv_path) != manifest["source_sha256"]:
        raise ValueError("Source checksum differs from frozen experiment")
    if manifest["final_test_scored"] or manifest["calibration_scored"]:
        raise ValueError("Training experiment did not reserve calibration and test")
    if manifest["feature_names"] != list(ORIGINATION_FEATURES):
        raise ValueError("Feature contract changed")
    for name, expected in manifest["artifacts_sha256"].items():
        if Path(name).name != name or "/" in name or "\\" in name:
            raise ValueError("Artifact name must stay within run directory")
        if digest(run_dir / name) != expected:
            raise ValueError(f"Artifact checksum mismatch: {name}")
    paths = [
        inspect.getfile(run_origination_experiment),
        inspect.getfile(OriginationFeatures),
        inspect.getfile(ModelConfig),
        inspect.getfile(binary_metrics),
    ]
    for path in paths:
        if digest(path) != manifest["source_code_sha256"][Path(path).name]:
            raise ValueError(f"Frozen base-model code changed: {Path(path).name}")
    for name, expected in manifest["versions"].items():
        if version(name) != expected:
            raise ValueError(f"Frozen dependency version changed: {name}")
    config = ModelConfig.model_validate(manifest["config"])
    frame = load_origination_csv(csv_path).frame.reset_index(drop=True)
    splits = split_origination(frame, config, manifest["seed"])
    saved = pd.read_csv(run_dir / "split_assignments.csv")
    groups = pd.util.hash_pandas_object(frame.loc[:, ORIGINATION_FEATURES], index=False).to_numpy()
    if not np.array_equal(saved.row_position, np.arange(len(frame))) or not np.array_equal(
        saved.feature_group, groups
    ):
        raise ValueError("Frozen row positions or predictor groups changed")
    for name, rows in splits.items():
        expected = manifest["partitions"][name]
        if (
            digest_positions(rows) != expected["row_positions_sha256"]
            or len(rows) != expected["rows"]
            or int(frame.iloc[rows][ORIGINATION_TARGET].sum()) != expected["bad_count"]
            or not np.array_equal(saved.loc[saved.partition == name, "row_position"], rows)
        ):
            raise ValueError(f"Frozen partition changed: {name}")
    return manifest, config, frame, splits, groups


def digest_positions(rows):
    return sha256(np.asarray(rows, dtype="<i8").tobytes()).hexdigest()


def run_validation(csv_path, run_dir, output_dir, config=None):
    config = config or ValidationConfig()
    directory, run_dir = Path(output_dir), Path(run_dir)
    if directory.exists() and any(directory.iterdir()):
        raise FileExistsError("Validation output is not empty; choose a new directory")
    manifest, model_config, frame, splits, groups = verify_experiment(csv_path, run_dir)
    X, y = frame.loc[:, ORIGINATION_FEATURES], frame[ORIGINATION_TARGET].astype(int)
    cal, dev, test = (splits[name] for name in ("calibration", "development", "test"))
    if (
        min(int(y.iloc[cal].sum()), int((1 - y.iloc[cal]).sum()))
        < config.minimum_calibration_events
    ):
        raise ValueError("Insufficient calibration outcomes")
    pipelines, calibrators, edges, dev_metrics, choices = {}, {}, {}, {}, {}
    kinds = [model_config.baseline, model_config.challenger]
    methods = model_config.calibration_methods
    directory.mkdir(parents=True, exist_ok=True)
    threshold = model_config.classification_threshold
    for kind in kinds:
        bundle = joblib.load(run_dir / f"{kind}.joblib")
        if (
            bundle["model_kind"] != kind
            or bundle["metadata"]["source_sha256"] != manifest["source_sha256"]
        ):
            raise ValueError("Model bundle metadata mismatch")
        pipeline = pipelines[kind] = bundle["pipeline"]
        raw_cal = predict_probability(pipeline, X.iloc[cal])
        raw_dev = predict_probability(pipeline, X.iloc[dev])
        dev_metrics[kind], calibrators[kind], edges[kind] = {}, {}, {}
        for method in methods:
            calibrator = ProbabilityCalibrator(method, config.probability_epsilon).fit(
                raw_cal, y.iloc[cal]
            )
            calibrators[kind][method] = calibrator
            edges[kind][method] = calibration_edges(
                calibrator.transform(raw_cal), config.calibration_bins
            )
            dev_metrics[kind][method] = binary_metrics(
                y.iloc[dev], calibrator.transform(raw_dev), threshold
            )
        choices[kind] = min(
            methods,
            key=lambda method: (
                dev_metrics[kind][method][config.selection_metric],
                dev_metrics[kind][method]["brier"],
                methods.index(method),
            ),
        )
    preferred = min(
        kinds,
        key=lambda kind: (
            dev_metrics[kind][choices[kind]][config.selection_metric],
            kinds.index(kind),
        ),
    )
    selection = {
        "selected_methods": choices,
        "preferred_candidate": preferred,
        "selection_partition": "development",
        "fit_partition": "calibration",
        "selection_metric": config.selection_metric,
        "development_metrics": dev_metrics,
        "parameters": {
            kind: {method: c.parameters() for method, c in variants.items()}
            for kind, variants in calibrators.items()
        },
        "config": config.model_dump(),
        "test_used_for_selection": False,
    }
    write_json(directory / "selection.json", selection)
    for kind in kinds:
        joblib.dump(
            CalibratedPDModel(pipelines[kind], calibrators[kind][choices[kind]]),
            directory / f"{kind}_selected.joblib",
        )
    lock = {
        "source_sha256": manifest["source_sha256"],
        "model_hashes": {kind: manifest["artifacts_sha256"][f"{kind}.joblib"] for kind in kinds},
        "methods": methods,
        "choices": choices,
        "preferred_candidate": preferred,
        "selection_metric": config.selection_metric,
        "epsilon": config.probability_epsilon,
        "calibration_code_sha256": digest(inspect.getfile(ProbabilityCalibrator)),
    }
    lock_hash = sha256(json.dumps(lock, sort_keys=True).encode()).hexdigest()
    marker = run_dir / "test_consumption.json"
    fresh = not marker.exists()
    if fresh:
        with marker.open("x", encoding="utf-8") as handle:
            json.dump(
                {
                    "selection_sha256": lock_hash,
                    "selection": lock,
                    "first_validation_directory": str(directory.resolve()),
                    "status": "test access locked; consumed even if interrupted",
                },
                handle,
                indent=2,
            )
    elif json.loads(marker.read_text(encoding="utf-8"))["selection_sha256"] != lock_hash:
        raise ValueError(
            "Test already consumed with different choices; use a new independently held-out sample"
        )
    predictions = pd.DataFrame({"row_position": test, "label": y.iloc[test].to_numpy()})
    final_metrics, reliability, segments, selected_predictions = {}, {}, {}, {}
    for kind in kinds:
        raw_test = predict_probability(pipelines[kind], X.iloc[test])
        final_metrics[kind], reliability[kind] = {}, {}
        for method in methods:
            p = calibrators[kind][method].transform(raw_test)
            predictions[f"{kind}__{method}"] = p
            final_metrics[kind][method] = binary_metrics(y.iloc[test], p, threshold)
            reliability[kind][method] = reliability_diagnostics(
                y.iloc[test], p, edges[kind][method], config.confidence_level
            )
            if method == choices[kind]:
                selected_predictions[kind] = p
                segments[kind] = segment_diagnostics(
                    X.iloc[test], y.iloc[test], p, config, threshold
                )
    uncertainty = group_bootstrap_comparison(
        y.iloc[test],
        selected_predictions,
        groups[test],
        config.bootstrap_samples,
        config.confidence_level,
        config.bootstrap_seed,
    )
    predictions.to_csv(directory / "test_predictions.csv", index=False)
    result = {
        "package_version": __version__,
        "target_semantics": manifest["target_semantics"],
        "validation_type": "grouped cross-sectional final holdout; not out-of-time",
        "fresh_test_access": fresh,
        "selection_sha256": lock_hash,
        "selection": selection,
        "source_sha256": manifest["source_sha256"],
        "partitions": manifest["partitions"],
        "final_metrics": final_metrics,
        "reliability": reliability,
        "segments": segments,
        "uncertainty": uncertainty,
        "missingness_by_partition": {
            name: X.iloc[rows].isna().mean().to_dict() for name, rows in splits.items()
        },
        "versions": {
            name: version(name) for name in (*manifest["versions"], "scipy", "matplotlib")
        },
        "limitations": [
            "No observation dates or contractual-default provenance",
            "Predictor groups do not identify borrowers; residual dependence may remain",
            "Bootstrap is conditional on fitted models, excluding retraining uncertainty",
            "Segment diagnostics are not a fairness certification",
            "Final-test benchmarks cannot change development-selected choices",
        ],
    }
    from credit_risk.validation.plots import plot_validation

    plot_validation(result, y.iloc[test], selected_predictions, directory)
    result["artifacts_sha256"] = {
        path.name: digest(path) for path in sorted(directory.iterdir()) if path.is_file()
    }
    write_json(directory / "validation.json", result)
    return result
